ktor:
  deployment:
    port: 8000
  application:
    modules:
      - io.nicronomicon.oracle.ApplicationKt.module
  filesystem:
    messages: "./storage/messages"
    prompts: "./storage/prompts"
  security:
    openAI: "$OPENAI_API_KEY"